print("What is your name?")
name = input()
print(f"It is nice to meet you {name}")
print ("how old are you (in years)")
years = int(input())
print ("how tall are you (in meters)")
meters = float(input())
print ("how much do you weight (in kilograms)")
kilograms = float(input())

bmi = kilograms / (meters ** 2 )
print(" name yor are years years old and your BMI is")
