print("welcome to COM411!")
print ("In week 1 we will learn ....")
print("... how to use Git and GitHub")
print("... How to output to the screen")
print ( "... How to get user input " )
print ("I hope you enjoying the lesson thus far ")
print("\n displays a new line")
print("\t Display a tab space")
print("\\ display a back slash")
print("\" Display a double quote")
print("\t I am programming!")
print("##########")
print("#        #")
print("#        #")
print("##########")
print("Please enter a character for the eye")
eye = input()
print("The robots expression is now as follows:")
print("##########")
print("#  0  0  #")
print("#   ---  #")
print("##########")